security:
    providers:
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|normalize.css|images|js)/
            security: false

        default:
            anonymous: ~
